from .deduction2025_model import Deduction2025Model
from .deduction_model import DeductionModel
from .goal_model import GoalModel
from .mutual_fund_model import MutualFundModel
from .nav_history_model import NavHistoryModel
from .notification_model import NotificationModel
from .performance_mutual_funds_model import PerformanceMutualFundsModel
from .portfolio_model import PortfolioModel
from .prediction_trend_funds_model import PredictionTrendFundsModel
from .tax_model import TaxModel
from .transaction_model import TransactionModel
from .user_model import UserModel
from .models import Base